# Generated by Django 3.0.5 on 2024-10-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0002_auto_20241009_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientaccount',
            name='medical_records_photo',
            field=models.ImageField(blank=True, null=True, upload_to='medical_records/'),
        ),
        migrations.AddField(
            model_name='patientaccount',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='patient_photos/'),
        ),
        migrations.AddField(
            model_name='patientaccount',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
    ]
