# Generated by Django 3.0.5 on 2024-10-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0003_auto_20241009_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoraccount',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
